#服务名称
spring:
  application:
    name: config-server
  #服务的git仓库地址
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ys97/springCloudConfig.git
          #配置文件所在的目录
          search-paths: /**
        native:
          search-locations: file:///D:/springCloudConfig
      #配置文件所在的分支
      label: master
    #git仓库的用户名
    #      username: 111111
    #git仓库的密码
  #      password: 111111
  #服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  #服务端口
server:
  port: 8888