server:
  port: 8010
spring:
  application:
    name: app-order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

ribbon:
  #建立连接
  ReadTimeout: 5000
  #读取资源
  ConnectTimeout: 5000
  #开启熔断器
feign:
  hystrix:
    enabled: true