eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 80
spring:
  application:
    name: zuul
#  cloud:
#    config:
#      profile: dev
#      #    uri: http://localhost:8888
#      discovery:
#        service-id: config-server
#        enabled: true
zuul:
  routes:
    api-a:
      path: /api-member/**
      serviceId: app-member
    api-b:
      path: /api-order/**
      serviceId: app-order
management:
  endpoints:
    web:
      exposure:
        include: "*"